#define IFTTT_EVENT "---YOUR IFTTT EVENT---"
#define IFTTT_KEY "---YOUR IFTT KEY---"

#define ESP_LED LED_BUILTIN

#define SENSOR_PIN D1
#define SENSOR_PIN_INVERTED D2

#define WPS_PIN D3
#define WPS_LED LED_BUILTIN

#define OPENER_PIN D5
#define CONTACT_DURATION 2000

#define USERNAME "---YOUR USERNAME---"
#define PASSWORD "---YOUR PASSWORD---"
